/**
 * One message, several channels.
 *
 * Announcements and bulk SMS were two unrelated features. Announcements were 49 lines that wrote a
 * row and fanned out to nobody; SMS had all the audience machinery and none of the portal. A head
 * wanting to tell families about Friday's closure wrote it twice, in two places, and the two said
 * slightly different things by the time they were sent.
 *
 * ## The two audiences were orthogonal all along
 *
 * SMS meant ALL | CLASS | LEVEL | CUSTOM — *which people*. An announcement meant
 * ALL | GUARDIANS | STUDENTS — *which portals*. Those answer different questions, so they are
 * separate fields here (`audienceScope`, `audienceRoles`) rather than one confused enum.
 *
 * Splitting them also makes a dead field live. `Announcement.audience` was read by the guardian
 * portal and the student portal but written by nobody, so every notice was "ALL" whatever the
 * school intended. It is now derived from `audienceRoles`, and those two readers become correct
 * for the first time.
 *
 * ## What a broadcast is, and is not
 *
 * It is not a delivery table. It EMITS: an Announcement for the portals, SmsMessage rows for
 * texts, BroadcastDelivery rows for email, SocialPost rows for social. One unified delivery table
 * would have swallowed the SMS credit ledger, the messaging screen's filters, and the four
 * automated senders that write SmsMessage directly with their own semantic batch ids — none of
 * which are broadcasts.
 */
import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Injectable,
  Logger,
  Module,
  NotFoundException,
  Param,
  Post,
  Query,
  StreamableFile,
  UploadedFile,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ArrayNotEmpty,
  IsArray,
  IsIn,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';
import { AuthUser, CurrentUser, RequireEntitlement, RequirePermission } from '../common/auth';
import { PrismaService } from '../prisma/prisma.service';
import { EmailModule, EmailService } from '../email/email.module';
import { SmsModule, SmsService } from '../sms/sms.module';
import { SocialService } from '../social/social.service';
import { normalizeMsisdn } from '../common/phone';
import { IMAGE_TYPES, MAX_UPLOAD_BYTES, objectKey, storage } from '../common/storage';
import { PageQuery, pageArgs, toPage } from '../common/list-query';

export const CHANNELS = ['PORTAL', 'SMS', 'EMAIL', 'SOCIAL'] as const;
export type Channel = (typeof CHANNELS)[number];
const SCOPES = ['ALL', 'CLASS', 'LEVEL', 'ROUTE', 'CUSTOM'] as const;
const ROLES = ['GUARDIANS', 'STUDENTS', 'STAFF'] as const;

class CreateBroadcastDto {
  @IsString() @MinLength(3) @MaxLength(140) title: string;
  @IsString() @MinLength(3) @MaxLength(4000) body: string;

  @IsIn(SCOPES) audienceScope: (typeof SCOPES)[number];
  @IsOptional() @IsString() classId?: string;
  @IsOptional() @IsString() levelId?: string;
  @IsOptional() @IsString() routeId?: string;
  @IsOptional() @IsArray() @IsString({ each: true }) recipients?: string[];

  @IsArray() @ArrayNotEmpty() @IsIn(ROLES, { each: true }) audienceRoles: string[];
  @IsArray() @ArrayNotEmpty() @IsIn(CHANNELS, { each: true }) channels: Channel[];

  /**
   * Generated by the composer, once per message.
   *
   * The only thing that makes a double-submit harmless: `SmsMessage.batchId` is minted server-side
   * from the clock, so two clicks a second apart produce two batches and two sends. This is
   * unique per school, so the second insert loses.
   */
  @IsString() @MinLength(8) @MaxLength(64) idempotencyKey: string;

  /** Media already uploaded against a draft, to attach on send. */
  @IsOptional() @IsArray() @IsString({ each: true }) mediaIds?: string[];
}

const EMERGENCY_KINDS = ['LOCKDOWN', 'EVACUATION', 'ALL_CLEAR', 'GENERAL'] as const;

/** The SMS prefix that makes a text unmistakable at a glance, before a word is read. */
const EMERGENCY_PREFIX: Record<(typeof EMERGENCY_KINDS)[number], string> = {
  LOCKDOWN: 'LOCKDOWN',
  EVACUATION: 'EVACUATION',
  ALL_CLEAR: 'ALL CLEAR',
  GENERAL: 'URGENT',
};

class EmergencyDto {
  @IsIn(EMERGENCY_KINDS) kind: (typeof EMERGENCY_KINDS)[number];
  @IsString() @MinLength(10) @MaxLength(300) message: string;
  /** Same contract as a broadcast's idempotency key — a double-tap is one alert. */
  @IsString() @MinLength(8) @MaxLength(64) idempotencyKey: string;
}

/** Minimal shape of a Multer upload — avoids depending on @types/multer. */
interface UploadedFileLike {
  buffer: Buffer;
  originalname: string;
  mimetype: string;
  size: number;
}

@Injectable()
export class BroadcastsService {
  private readonly log = new Logger('Broadcasts');

  constructor(
    private db: PrismaService,
    private sms: SmsService,
    private email: EmailService,
    private social: SocialService,
  ) {}

  async list(auth: AuthUser, q: PageQuery) {
    const { skip, take, page, perPage } = pageArgs(q);
    const where = { schoolId: auth.schoolId };
    const [total, rows] = await Promise.all([
      this.db.broadcast.count({ where }),
      this.db.broadcast.findMany({
        where,
        // createdAt is not unique, so it alone lets OFFSET make rows unreachable when two
        // broadcasts share a timestamp. The id breaks the tie.
        orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
        skip,
        take,
        include: {
          media: { select: { id: true, filename: true, mimeType: true } },
          posts: { select: { platform: true, status: true, permalink: true, error: true } },
          _count: { select: { deliveries: true } },
        },
      }),
    ]);
    return toPage(rows, total, { page, perPage });
  }

  async detail(auth: AuthUser, id: string) {
    const b = await this.db.broadcast.findFirst({
      where: { id, schoolId: auth.schoolId },
      include: {
        media: true,
        deliveries: { orderBy: { createdAt: 'desc' }, take: 200 },
        posts: true,
      },
    });
    if (!b) throw new NotFoundException('Broadcast not found');
    return b;
  }

  /** Guardian phone numbers for the chosen scope. Mirrors SmsService, which owns the same rule. */
  private async resolvePhones(auth: AuthUser, dto: CreateBroadcastDto): Promise<string[]> {
    if (dto.audienceScope === 'CUSTOM') {
      return [
        ...new Set((dto.recipients ?? []).map(normalizeMsisdn).filter((x): x is string => !!x)),
      ];
    }
    const where: {
      schoolId: string;
      status: 'ACTIVE';
      classId?: string;
      classRoom?: { levelId: string };
      transportRider?: { routeId: string };
    } = { schoolId: auth.schoolId, status: 'ACTIVE' };
    if (dto.audienceScope === 'CLASS') {
      if (!dto.classId) throw new BadRequestException('Pick a class');
      where.classId = dto.classId;
    }
    if (dto.audienceScope === 'LEVEL') {
      if (!dto.levelId) throw new BadRequestException('Pick a level');
      where.classRoom = { levelId: dto.levelId };
    }
    if (dto.audienceScope === 'ROUTE') {
      if (!dto.routeId) throw new BadRequestException('Pick a route');
      where.transportRider = { routeId: dto.routeId };
    }
    const students = await this.db.student.findMany({
      where,
      select: {
        guardians: {
          // BLOCKED excluded even here, where a human picked the audience: "all guardians of
          // Basic 4" is a class, not a considered list of individuals, and nobody selecting it is
          // thinking about the one parent under a custody order.
          where: { isPrimary: true, custodyFlag: { not: 'BLOCKED' } },
          select: { guardian: { select: { phone: true } } },
        },
      },
    });
    return [
      ...new Set(
        students
          .flatMap((s) => s.guardians.map((g) => g.guardian.phone))
          .map(normalizeMsisdn)
          .filter((x): x is string => !!x),
      ),
    ];
  }

  /** Guardian email addresses for the chosen scope. Same custody rule as the phones. */
  private async resolveEmails(auth: AuthUser, dto: CreateBroadcastDto) {
    if (dto.audienceScope === 'CUSTOM') return [];
    const where: {
      schoolId: string;
      status: 'ACTIVE';
      classId?: string;
      classRoom?: { levelId: string };
      transportRider?: { routeId: string };
    } = { schoolId: auth.schoolId, status: 'ACTIVE' };
    if (dto.audienceScope === 'CLASS' && dto.classId) where.classId = dto.classId;
    if (dto.audienceScope === 'LEVEL' && dto.levelId) where.classRoom = { levelId: dto.levelId };
    if (dto.audienceScope === 'ROUTE' && dto.routeId) {
      where.transportRider = { routeId: dto.routeId };
    }

    const students = await this.db.student.findMany({
      where,
      select: {
        guardians: {
          where: { isPrimary: true, custodyFlag: { not: 'BLOCKED' } },
          select: { guardian: { select: { email: true, firstName: true, lastName: true } } },
        },
      },
    });
    const seen = new Map<string, string>();
    for (const s of students) {
      for (const g of s.guardians) {
        const e = g.guardian.email?.trim().toLowerCase();
        if (e && e.includes('@') && !seen.has(e)) {
          seen.set(e, `${g.guardian.firstName} ${g.guardian.lastName}`.trim());
        }
      }
    }
    return [...seen].map(([email, name]) => ({ email, name }));
  }

  /**
   * The `Announcement.audience` value for a set of portal roles.
   *
   * The readers in guardian.module and student-portal.module match on `['ALL', 'GUARDIANS']` and
   * `['ALL', 'STUDENTS']`, so ALL is what reaches both. STAFF-only notices are ALL too: the staff
   * dashboard reads every announcement without filtering, and there is no narrower value those
   * two readers would both ignore.
   */
  private announcementAudience(roles: string[]): string {
    const guardians = roles.includes('GUARDIANS');
    const students = roles.includes('STUDENTS');
    if (guardians && students) return 'ALL';
    if (guardians) return 'GUARDIANS';
    if (students) return 'STUDENTS';
    return 'ALL';
  }

  async create(auth: AuthUser, dto: CreateBroadcastDto) {
    if (dto.channels.includes('SMS') && !auth.permissions?.includes('comms.sms')) {
      throw new BadRequestException('You do not have permission to send SMS');
    }
    if (dto.channels.includes('SOCIAL') && !auth.permissions?.includes('comms.social')) {
      throw new BadRequestException('You do not have permission to post to social accounts');
    }
    /**
     * A picked list is a list of phone numbers and nothing else — there is no portal account
     * behind one, and no address to email. Silently doing nothing on those channels is how a
     * targeted message ("please see the bursar about your balance") ended up on the notice board
     * every family reads, so this refuses instead of half-sending.
     */
    if (dto.audienceScope === 'CUSTOM') {
      const impossible = dto.channels.filter((c) => c !== 'SMS');
      if (impossible.length > 0) {
        throw new BadRequestException(
          `A picked list can only be reached by SMS — there is no portal account or email address behind a phone number. Remove ${impossible.join(', ').toLowerCase()}.`,
        );
      }
    }

    // The unique constraint is the real guard; this only turns the second click into the first
    // broadcast rather than a 500.
    const existing = await this.db.broadcast.findFirst({
      where: { schoolId: auth.schoolId, idempotencyKey: dto.idempotencyKey },
    });
    if (existing) return this.detail(auth, existing.id);

    const broadcast = await this.db.broadcast.create({
      data: {
        schoolId: auth.schoolId,
        title: dto.title.trim(),
        body: dto.body.trim(),
        audienceScope: dto.audienceScope,
        classId: dto.classId,
        levelId: dto.levelId,
        routeId: dto.routeId,
        recipients: dto.recipients ?? [],
        audienceRoles: dto.audienceRoles,
        channels: dto.channels,
        idempotencyKey: dto.idempotencyKey,
        status: 'SENDING',
        createdById: auth.sub,
      },
    });

    if (dto.mediaIds?.length) {
      await this.db.broadcastMedia.updateMany({
        where: { id: { in: dto.mediaIds }, schoolId: auth.schoolId, broadcastId: '' },
        data: { broadcastId: broadcast.id },
      });
    }

    const results = await this.deliver(auth, broadcast.id, dto);

    const failed = results.filter((r) => !r.ok);
    const status =
      failed.length === 0 ? 'SENT' : failed.length === results.length ? 'FAILED' : 'PARTIAL';
    await this.db.broadcast.update({
      where: { id: broadcast.id },
      data: { status, sentAt: new Date() },
    });
    await this.db.audit(auth.schoolId, auth.sub, 'broadcast.send', 'Broadcast', broadcast.id, {
      channels: dto.channels,
      status,
    });

    return { ...(await this.detail(auth, broadcast.id)), results };
  }

  /**
   * An emergency alert: every family and every member of staff, at once, by SMS and portal.
   *
   * Deliberately a broadcast underneath — the record, the send log and the notice board all come
   * for free — but with the audience fixed to everyone and staff phones added, which an ordinary
   * broadcast never texts. Nothing here waits for quiet hours or asks about audience: by the time
   * someone with this permission is typing, the decision has been made.
   */
  async emergency(auth: AuthUser, dto: EmergencyDto) {
    const existing = await this.db.broadcast.findFirst({
      where: { schoolId: auth.schoolId, idempotencyKey: dto.idempotencyKey },
    });
    if (existing) return this.detail(auth, existing.id);

    const title = `${EMERGENCY_PREFIX[dto.kind]} — please read now`;
    const asBroadcast: CreateBroadcastDto = {
      title,
      body: dto.message.trim(),
      audienceScope: 'ALL',
      audienceRoles: ['GUARDIANS', 'STUDENTS', 'STAFF'],
      channels: ['PORTAL', 'SMS'],
      idempotencyKey: dto.idempotencyKey,
    };

    const broadcast = await this.db.broadcast.create({
      data: {
        schoolId: auth.schoolId,
        title,
        body: asBroadcast.body,
        audienceScope: 'ALL',
        recipients: [],
        audienceRoles: asBroadcast.audienceRoles,
        channels: asBroadcast.channels,
        idempotencyKey: dto.idempotencyKey,
        status: 'SENDING',
        createdById: auth.sub,
      },
    });

    const results = await this.deliver(auth, broadcast.id, asBroadcast);

    // Staff are not guardians, so the ordinary resolver never texts them — but a lockdown is
    // for the people in the building first.
    try {
      const staff = await this.db.user.findMany({
        // GUARDIAN-role principals are families, and their alert already went out above.
        where: {
          schoolId: auth.schoolId,
          active: true,
          phone: { not: null },
          role: { not: 'GUARDIAN' },
        },
        select: { phone: true },
      });
      const phones = [
        ...new Set(
          staff
            .map((s) => (s.phone ? normalizeMsisdn(s.phone) : null))
            .filter((x): x is string => !!x),
        ),
      ];
      if (phones.length > 0) {
        const r = await this.sms.sendToPhones({
          schoolId: auth.schoolId,
          phones,
          body: `${title}\n\n${asBroadcast.body}`,
          createdById: auth.sub,
          batchId: `BC-${broadcast.id}-STAFF`,
          broadcastId: broadcast.id,
        });
        results.push({
          channel: 'SMS',
          ok: r.sent > 0,
          detail: `Staff: ${r.sent} sent, ${r.failed} failed, ${r.skipped} skipped for credit`,
        });
      }
    } catch (e) {
      results.push({ channel: 'SMS', ok: false, detail: `Staff: ${String(e)}` });
    }

    const failed = results.filter((r) => !r.ok);
    const status =
      failed.length === 0 ? 'SENT' : failed.length === results.length ? 'FAILED' : 'PARTIAL';
    await this.db.broadcast.update({
      where: { id: broadcast.id },
      data: { status, sentAt: new Date() },
    });
    await this.db.audit(auth.schoolId, auth.sub, 'safety.emergency', 'Broadcast', broadcast.id, {
      kind: dto.kind,
      status,
    });
    return { ...(await this.detail(auth, broadcast.id)), results };
  }

  /**
   * Fan out, one channel at a time, and never let one channel's failure take the others down.
   *
   * A school that has run out of SMS credit still wants the notice on the portal and in the
   * inbox. Each channel reports its own outcome, and the broadcast's status is the summary.
   */
  private async deliver(auth: AuthUser, broadcastId: string, dto: CreateBroadcastDto) {
    const results: { channel: Channel; ok: boolean; detail: string }[] = [];

    if (dto.channels.includes('PORTAL')) {
      try {
        await this.db.announcement.create({
          data: {
            schoolId: auth.schoolId,
            title: dto.title.trim(),
            body: dto.body.trim(),
            audience: this.announcementAudience(dto.audienceRoles),
            // Carried onto the notice, so the portals can show it to the families it was meant
            // for. Without these a "Basic 4 trip on Friday" reached every family in the school.
            classId: dto.audienceScope === 'CLASS' ? dto.classId : null,
            levelId: dto.audienceScope === 'LEVEL' ? dto.levelId : null,
            routeId: dto.audienceScope === 'ROUTE' ? dto.routeId : null,
            broadcastId,
            createdById: auth.sub,
          },
        });
        results.push({ channel: 'PORTAL', ok: true, detail: 'Posted to the notice board' });
      } catch (e) {
        results.push({ channel: 'PORTAL', ok: false, detail: String(e) });
      }
    }

    if (dto.channels.includes('SMS')) {
      try {
        const phones = await this.resolvePhones(auth, dto);
        if (phones.length === 0) throw new Error('No guardian numbers matched');
        const r = await this.sms.sendToPhones({
          schoolId: auth.schoolId,
          phones,
          // The title carries the context a text has no room to establish otherwise.
          body: `${dto.title.trim()}\n\n${dto.body.trim()}`,
          createdById: auth.sub,
          batchId: `BC-${broadcastId}`,
          broadcastId,
        });
        results.push({
          channel: 'SMS',
          ok: r.sent > 0,
          detail: `${r.sent} sent, ${r.failed} failed, ${r.skipped} skipped for credit`,
        });
      } catch (e) {
        results.push({
          channel: 'SMS',
          ok: false,
          detail: e instanceof Error ? e.message : String(e),
        });
      }
    }

    if (dto.channels.includes('EMAIL')) {
      try {
        const targets = await this.resolveEmails(auth, dto);
        if (targets.length === 0) throw new Error('No guardian email addresses on file');
        let sent = 0;
        for (const t of targets) {
          // One row per recipient, written before the send. EmailService is fire-and-forget and
          // persists nothing at all, so without this the email channel would have no record that
          // it ran — the asymmetry that made "did the parents get it?" unanswerable for email.
          const row = await this.db.broadcastDelivery.upsert({
            where: {
              schoolId_broadcastId_channel_target: {
                schoolId: auth.schoolId,
                broadcastId,
                channel: 'EMAIL',
                target: t.email,
              },
            },
            create: {
              schoolId: auth.schoolId,
              broadcastId,
              channel: 'EMAIL',
              target: t.email,
            },
            update: {},
          });
          const ok = await this.email.send({
            to: t.email,
            toName: t.name,
            kind: 'broadcast',
            message: {
              subject: dto.title.trim(),
              text: dto.body.trim(),
              html: `<p>${dto.body.trim().replace(/\n/g, '<br>')}</p>`,
            },
          });
          if (ok) sent++;
          await this.db.broadcastDelivery.update({
            where: { id: row.id },
            data: {
              status: ok ? 'SENT' : 'FAILED',
              sentAt: ok ? new Date() : null,
              error: ok ? null : 'Provider did not accept the message',
            },
          });
        }
        results.push({ channel: 'EMAIL', ok: sent > 0, detail: `${sent}/${targets.length} sent` });
      } catch (e) {
        results.push({
          channel: 'EMAIL',
          ok: false,
          detail: e instanceof Error ? e.message : String(e),
        });
      }
    }

    if (dto.channels.includes('SOCIAL')) {
      try {
        const r = await this.social.publishBroadcast(auth.schoolId, broadcastId);
        results.push({
          channel: 'SOCIAL',
          ok: r.published > 0,
          detail: r.detail,
        });
      } catch (e) {
        results.push({
          channel: 'SOCIAL',
          ok: false,
          detail: e instanceof Error ? e.message : String(e),
        });
      }
    }

    return results;
  }

  /**
   * Attach an image before sending.
   *
   * Uploaded against `broadcastId: ''` and claimed by `create`, because Instagram and TikTok are
   * media-mandatory: the composer has to be able to attach a picture before it knows whether the
   * message will ever be sent.
   */
  async upload(auth: AuthUser, file: UploadedFileLike) {
    if (!file) throw new BadRequestException('No file uploaded');
    if (!IMAGE_TYPES.includes(file.mimetype)) {
      throw new BadRequestException('Attachments must be a JPEG, PNG or WebP image');
    }
    if (file.size > MAX_UPLOAD_BYTES) throw new BadRequestException('That image is too large');

    const id = `bm_${Date.now().toString(36)}`;
    const key = objectKey(auth.schoolId, 'broadcast', id, file.originalname);
    await storage().put(key, file.buffer, file.mimetype);
    return this.db.broadcastMedia.create({
      data: {
        schoolId: auth.schoolId,
        broadcastId: '',
        key,
        filename: file.originalname,
        mimeType: file.mimetype,
        sizeBytes: file.size,
      },
      select: { id: true, filename: true, mimeType: true, sizeBytes: true },
    });
  }

  async readMedia(auth: AuthUser, mediaId: string) {
    const m = await this.db.broadcastMedia.findFirst({
      where: { id: mediaId, schoolId: auth.schoolId },
    });
    if (!m) throw new NotFoundException('Attachment not found');
    return { buf: await storage().get(m.key), mimeType: m.mimeType };
  }
}

@Controller('broadcasts')
export class BroadcastsController {
  constructor(private svc: BroadcastsService) {}

  @Get()
  list(@CurrentUser() user: AuthUser, @Query() q: PageQuery) {
    return this.svc.list(user, q);
  }

  @Get(':id')
  detail(@CurrentUser() user: AuthUser, @Param('id') id: string) {
    return this.svc.detail(user, id);
  }

  @Post()
  @RequirePermission('comms.announce')
  @RequireEntitlement('comms.announcements')
  create(@CurrentUser() user: AuthUser, @Body() dto: CreateBroadcastDto) {
    return this.svc.create(user, dto);
  }

  @Post('emergency')
  @RequirePermission('safety.emergency')
  @RequireEntitlement('safety.emergency')
  emergency(@CurrentUser() user: AuthUser, @Body() dto: EmergencyDto) {
    return this.svc.emergency(user, dto);
  }

  @Post('media')
  @RequirePermission('comms.announce')
  @UseInterceptors(FileInterceptor('file'))
  upload(@CurrentUser() user: AuthUser, @UploadedFile() file: UploadedFileLike) {
    return this.svc.upload(user, file);
  }

  @Get('media/:id')
  async media(@CurrentUser() user: AuthUser, @Param('id') id: string) {
    const { buf, mimeType } = await this.svc.readMedia(user, id);
    return new StreamableFile(buf, { type: mimeType });
  }
}

/**
 * The notice board, unchanged.
 *
 * Kept because three readers already depend on it — the staff dashboard, the guardian portal and
 * the student portal — and because a school posting a notice to its own board should not have to
 * think about channels at all. What changed is that a broadcast can now write to it too.
 */
@Controller('announcements')
export class AnnouncementsController {
  constructor(private db: PrismaService) {}

  @Get()
  list(@CurrentUser() user: AuthUser) {
    return this.db.announcement.findMany({
      where: { schoolId: user.schoolId },
      orderBy: { publishedAt: 'desc' },
      take: 50,
    });
  }
}

@Module({
  // SocialModule is @Global, so only these two need naming.
  imports: [SmsModule, EmailModule],
  controllers: [BroadcastsController, AnnouncementsController],
  providers: [BroadcastsService],
  exports: [BroadcastsService],
})
export class BroadcastsModule {}
